// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWds4RQNVH-l6daV0PhZSQIZg059g3iRs',
    appId: '1:334239902633:web:32d37fca4955e3429f32b8',
    messagingSenderId: '334239902633',
    projectId: 'soj-gym',
    authDomain: 'soj-gym.firebaseapp.com',
    databaseURL: 'https://soj-gym-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soj-gym.appspot.com',
    measurementId: 'G-H1NRD77N5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGZAKZGQBsyrpY07EYhrfYWWXJM8rQLY',
    appId: '1:334239902633:android:589661a8a272617e9f32b8',
    messagingSenderId: '334239902633',
    projectId: 'soj-gym',
    databaseURL: 'https://soj-gym-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soj-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrx43yhsw-2Yp1E1wkBaAHuetrxPtH6g',
    appId: '1:334239902633:ios:8355314a74e851aa9f32b8',
    messagingSenderId: '334239902633',
    projectId: 'soj-gym',
    databaseURL: 'https://soj-gym-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soj-gym.appspot.com',
    iosClientId: '334239902633-c8bbejdd2k1apqsn9hmunel8btgbd6jm.apps.googleusercontent.com',
    iosBundleId: 'medk.bjj.management.bjjMembersManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrx43yhsw-2Yp1E1wkBaAHuetrxPtH6g',
    appId: '1:334239902633:ios:8355314a74e851aa9f32b8',
    messagingSenderId: '334239902633',
    projectId: 'soj-gym',
    databaseURL: 'https://soj-gym-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'soj-gym.appspot.com',
    iosClientId: '334239902633-c8bbejdd2k1apqsn9hmunel8btgbd6jm.apps.googleusercontent.com',
    iosBundleId: 'medk.bjj.management.bjjMembersManagement',
  );
}
